added js logic Coha3093O+NHughes@NHughes MINGW64 ~ $ cd source/repos/webapps/HR-Training
GPDCO+NHughes@NHughes MINGW64 ~/source/repos/webapps/HR-Training
(forecasting)
$ git add --all

GPDCO+NHughes@NHughes MINGW64 ~/source/repos/webapps/HR-Training
(forecasting)
$ git commit
[forecasting 32ea959] some changes needs testing
 5 files changed, 12 insertions(+), 106 deletions(-)
  create mode 100644 HR-Training/Views/Admin/_ForecastingLoading.cshtml

  GPDCO+NHughes@NHughes MINGW64 ~/source/repos/webapps/HR-Training
  (forecasting)
  $ git push
  Enumerating objects: 24, done.
  Counting objects: 100% (24/24), done.
  Delta compression using up to 8 threads
  Compressing objects: 100% (13/13), done.
  Writing objects: 100% (13/13), 1.29 KiB | 1.29 MiB/s, done.
  Total 13 (delta 10), reused 0 (delta 0), pack-reused 0 (from 0)
  remote: Resolving deltas: 100% (10/10), completed with 10 local
  objects.
  To https://github.com/GPD-Group/HR-Training.git
     38cdbae..32ea959  forecasting -> forecasting

     GPDCO+NHughes@NHughes MINGW64 ~/source/repos/webapps/HR-Training
     (forecasting)
     $ cd webapps/GPDForms
     bash: cd: webapps/GPDForms: No such file or directory

     GPDCO+NHughes@NHughes MINGW64 ~/source/repos/webapps/HR-Training
     (forecasting)
     $ cd source/repos/webapps/GPDForms
     bash: cd: source/repos/webapps/GPDForms: No such file or directory

     GPDCO+NHughes@NHughes MINGW64 ~/source/repos/webapps/HR-Training
     (forecasting)
     $ cd C:/users/source/repos/webapps/GPDForms
     bash: cd: C:/users/source/repos/webapps/GPDForms: No such file or
     directory

     GPDCO+NHughes@NHughes MINGW64 ~/source/repos/webapps/HR-Training
     (forecasting)
     $ cd C:/users/nhughes/source/repos/webapps/GPDForms

     GPDCO+NHughes@NHughes MINGW64
     /c/users/nhughes/source/repos/webapps/GPDForms (main)
     $ git switch Forms2-Refactor
     fatal: invalid reference: Forms2-Refactor

     GPDCO+NHughes@NHughes MINGW64
     /c/users/nhughes/source/repos/webapps/GPDForms (main)
     $ git fetch
     From https://github.com/GPD-Group/GPDForms
      * [new branch]      Forms2-Refactor -> origin/Forms2-Refactor

      GPDCO+NHughes@NHughes MINGW64
      /c/users/nhughes/source/repos/webapps/GPDForms (main)
      $ git pull
      error: Your local changes to the following files would be
      overwritten by merge:
              GPD Forms/GPD Forms.csproj
	      Please commit your changes or stash them before you merge.
	      Aborting
	      Updating 1132ce3..1407be5

	      GPDCO+NHughes@NHughes MINGW64
	      /c/users/nhughes/source/repos/webapps/GPDForms (main)
	      $ git switch Forms2-Refactor
	      error: Your local changes to the following files would be
	      overwritten by checkout:
	              GPD Forms/GPD Forms.csproj
		      Please commit your changes or stash them before
		      you switch branches.
		      Aborting

		      GPDCO+NHughes@NHughes MINGW64
		      /c/users/nhughes/source/repos/webapps/GPDForms
		      (main)
		      $ git add --all

		      GPDCO+NHughes@NHughes MINGW64
		      /c/users/nhughes/source/repos/webapps/GPDForms
		      (main)
		      $ git stash
		      Saved working directory and index state WIP on
		      main: 1132ce3 Merge pull request #21 from
		      GPD-Group/NHughes333-patch-1

		      GPDCO+NHughes@NHughes MINGW64
		      /c/users/nhughes/source/repos/webapps/GPDForms
		      (main)
		      $ git switch Forms2-Refactor
		      Switched to a new branch 'Forms2-Refactor'
		      branch 'Forms2-Refactor' set up to track
		      'origin/Forms2-Refactor'.

		      GPDCO+NHughes@NHughes MINGW64
		      /c/users/nhughes/source/repos/webapps/GPDForms
		      (Forms2-Refactor)
		      $ git add --all

		      GPDCO+NHughes@NHughes MINGW64
		      /c/users/nhughes/source/repos/webapps/GPDForms
		      (Forms2-Refactor)
		      $ git commit
		      [Forms2-Refactor 6396e61] start of create
		      method(s)
		       2 files changed, 180 insertions(+), 4
		       deletions(-)
		        create mode 100644 GPD
			Forms/Controllers/FormsController.Create.cs
			got
			GPDCO+NHughes@NHughes MINGW64
			/c/users/nhughes/source/repos/webapps/GPDForms
			(Forms2-Refactor)
			$ git push
			Enumerating objects: 10, done.
			Counting objects: 100% (10/10), done.
			Delta compression using up to 8 threads
			Compressing objects: 100% (6/6), done.
			Writing objects: 100% (6/6), 2.79 KiB | 1.39
			MiB/s, done.
			Total 6 (delta 4), reused 0 (delta 0),
			pack-reused 0 (from 0)
			remote: Resolving deltas: 100% (4/4), completed
			with 4 local objects.
			To https://github.com/GPD-Group/GPDForms.git
			   1407be5..6396e61  Forms2-Refactor ->
			   Forms2-Refactor

			   GPDCO+NHughes@NHughes MINGW64
			   /c/users/nhughes/source/repos/webapps/GPDForms
			   (Forms2-Refactor)
			   $ git commit -a --all
			   [Forms2-Refactor 0afcfe2] genaric form start
			    1 file changed, 1 insertion(+), 1
			    deletion(-)
			    git
			    GPDCO+NHughes@NHughes MINGW64
			    /c/users/nhughes/source/repos/webapps/GPDForms
			    (Forms2-Refactor)
			    $ git push
			    Enumerating objects: 9, done.
			    Counting objects: 100% (9/9), done.
			    Delta compression using up to 8 threads
			    Compressing objects: 100% (5/5), done.
			    Writing objects: 100% (5/5), 426 bytes |
			    426.00 KiB/s, done.
			    Total 5 (delta 4), reused 0 (delta 0),
			    pack-reused 0 (from 0)
			    remote: Resolving deltas: 100% (4/4),
			    completed with 4 local objects.
			    To https://github.com/GPD-Group/GPDForms.git
			       6396e61..0afcfe2  Forms2-Refactor ->
			       Forms2-Refactor

			       GPDCO+NHughes@NHughes MINGW64
			       /c/users/nhughes/source/repos/webapps/GPDForms
			       (Forms2-Refactor)
			       $ git commit -a --all
			       On branch Forms2-Refactor
			       Your branch is up to date with
			       'origin/Forms2-Refactor'.

			       Untracked files:
			         (use "git add <file>..." to include in
				 what will be committed)
				         GPD Forms/Models/FormModel.cs

					 nothing added to commit but
					 untracked files present (use
					 "git add" to track)
					 i
					 GPDCO+NHughes@NHughes MINGW64
					 /c/users/nhughes/source/repos/webapps/GPDForms
					 (Forms2-Refactor)
					 $ git add --all
					 GPDCO+NHughes@NHughes MINGW64
					 /c/users/nhughes/source/repos/webapps/GPDForms
					 (Forms2-Refactor)
					 $ git commit
					 [Forms2-Refactor 7f76464] more
					 genaric form
					  1 file changed, 32
					  insertions(+)
					   create mode 100644 GPD
					   Forms/Models/FormModel.cs

					   GPDCO+NHughes@NHughes MINGW64
					   /c/users/nhughes/source/repos/webapps/GPDForms
					   (Forms2-Refactor)
					   $ git push
					   Enumerating objects: 8, done.
					   Counting objects: 100% (8/8),
					   done.
					   Delta compression using up to
					   8 threads
					   Compressing objects: 100%
					   (5/5), done.
					   Writing objects: 100% (5/5),
					   909 bytes | 181.00 KiB/s,
					   done.
					   Total 5 (delta 3), reused 0
					   (delta 0), pack-reused 0
					   (from 0)
					   remote: Resolving deltas:
					   100% (3/3), completed with 3
					   local objects.
					   To
					   https://github.com/GPD-Group/GPDForms.git
					      0afcfe2..7f76464
					      Forms2-Refactor ->
					      Forms2-Refactor

					      GPDCO+NHughes@NHughes
					      MINGW64
					      /c/users/nhughes/source/repos/webapps/GPDForms
					      (Forms2-Refactor)
					      $ cd
					      ~/source/repos/webapps/HR-Training

					      GPDCO+NHughes@NHughes
					      MINGW64
					      ~/source/repos/webapps/HR-Training
					      (forecasting)
					      $ git commit -a --all
					      [forecasting 21898fe] DI
					      exception
					       2 files changed, 2
					       insertions(+), 2
					       deletions(-)

					       GPDCO+NHughes@NHughes
					       MINGW64
					       ~/source/repos/webapps/HR-Training
					       (forecasting)
					       $ git push
					       Enumerating objects: 15,
					       done.
					       Counting objects: 100%
					       (15/15), done.
					       Delta compression using
					       up to 8 threads
					       Compressing objects: 100%
					       (8/8), done.
					       Writing objects: 100%
					       (8/8), 740 bytes | 370.00
					       KiB/s, done.
					       Total 8 (delta 6), reused
					       0 (delta 0), pack-reused
					       0 (from 0)
					       remote: Resolving deltas:
					       100% (6/6), completed
					       with 6 local objects.
					       To
					       https://github.com/GPD-Group/HR-Training.git
					          32ea959..21898fe
						  forecasting ->
						  forecasting

						  GPDCO+NHughes@NHughes
						  MINGW64
						  ~/source/repos/webapps/HR-Training
						  (forecasting)
						  $ cd ~/source/repos

						  GPDCO+NHughes@NHughes
						  MINGW64 ~/source/repos
						  $ git clone
						  i